[01.03.2024 00:45:41][INFO] Update id=740518519 is handled. Duration 197 ms by bot id=6649228926
[01.03.2024 00:46:01][INFO] Update id=740518520 is handled. Duration 229 ms by bot id=6649228926
[01.03.2024 00:47:09][INFO] Update id=740518521 is handled. Duration 188 ms by bot id=6649228926
[01.03.2024 00:47:23][INFO] Update id=740518522 is handled. Duration 89 ms by bot id=6649228926
[01.03.2024 00:47:36][INFO] Update id=740518523 is not handled. Duration 3 ms by bot id=6649228926
[01.03.2024 00:47:36][ERROR] Cause exception while process update id=740518523 by bot id=6649228926
AttributeError: 'Scene' object has no attribute 'dealer'
Traceback (most recent call last):
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/handlers/rooms_manager.py", line 193, in in_game
    active_user, passive_user = room.solve_players()
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/core/scene.py", line 288, in solve_players
    if self.dealer.turn_int % 2 == 0:
       ^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'dealer'
[01.03.2024 00:48:02][INFO] Update id=740518524 is not handled. Duration 1 ms by bot id=6649228926
[01.03.2024 00:48:02][ERROR] Cause exception while process update id=740518524 by bot id=6649228926
AttributeError: 'Scene' object has no attribute 'dealer'
Traceback (most recent call last):
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/handlers/rooms_manager.py", line 193, in in_game
    active_user, passive_user = room.solve_players()
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/core/scene.py", line 288, in solve_players
    if self.dealer.turn_int % 2 == 0:
       ^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'dealer'
[01.03.2024 00:48:13][INFO] Update id=740518525 is handled. Duration 173 ms by bot id=6649228926
[01.03.2024 00:48:16][INFO] Update id=740518526 is handled. Duration 511 ms by bot id=6649228926
[01.03.2024 00:48:24][INFO] Update id=740518527 is handled. Duration 76 ms by bot id=6649228926
[01.03.2024 00:48:33][INFO] Update id=740518528 is handled. Duration 199 ms by bot id=6649228926
[01.03.2024 00:48:37][INFO] Update id=740518529 is handled. Duration 217 ms by bot id=6649228926
[01.03.2024 00:48:40][INFO] Update id=740518530 is handled. Duration 337 ms by bot id=6649228926
[01.03.2024 00:48:44][INFO] Update id=740518531 is handled. Duration 270 ms by bot id=6649228926
[01.03.2024 00:48:47][INFO] Update id=740518532 is handled. Duration 311 ms by bot id=6649228926
[01.03.2024 00:48:50][INFO] Update id=740518533 is handled. Duration 63 ms by bot id=6649228926
[01.03.2024 00:49:08][INFO] Update id=740518534 is handled. Duration 424 ms by bot id=6649228926
[01.03.2024 00:49:16][INFO] Update id=740518535 is handled. Duration 206 ms by bot id=6649228926
[01.03.2024 00:49:19][INFO] Update id=740518536 is handled. Duration 139 ms by bot id=6649228926
[01.03.2024 00:49:22][INFO] Update id=740518537 is handled. Duration 294 ms by bot id=6649228926
[01.03.2024 00:49:27][INFO] Update id=740518538 is handled. Duration 287 ms by bot id=6649228926
[01.03.2024 00:49:30][INFO] Update id=740518539 is handled. Duration 224 ms by bot id=6649228926
[01.03.2024 00:49:33][INFO] Update id=740518540 is handled. Duration 281 ms by bot id=6649228926
[01.03.2024 00:49:41][INFO] Update id=740518541 is handled. Duration 213 ms by bot id=6649228926
[01.03.2024 00:49:46][INFO] Update id=740518542 is handled. Duration 212 ms by bot id=6649228926
[01.03.2024 00:49:48][INFO] Update id=740518543 is handled. Duration 338 ms by bot id=6649228926
[01.03.2024 00:49:53][INFO] Update id=740518544 is handled. Duration 245 ms by bot id=6649228926
[01.03.2024 00:49:55][INFO] Update id=740518545 is not handled. Duration 2 ms by bot id=6649228926
[01.03.2024 00:49:55][ERROR] Cause exception while process update id=740518545 by bot id=6649228926
ValidationError: 1 validation error for PlayerModel
hp
  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/greater_than_equal
Traceback (most recent call last):
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/handlers/rooms_manager.py", line 217, in in_game
    turn_result = room.make_turn(action, message.chat.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/core/scene.py", line 135, in make_turn
    action_results = self.shotgun.shot(player=target)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/core/shotgun.py", line 48, in shot
    player.take_damage(self.damage)
  File "/home/karo-work/buckshot-evo/app/core/player.py", line 83, in take_damage
    self.data.hp -= damage
    ^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/pydantic/main.py", line 786, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PlayerModel
hp
  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/greater_than_equal
[01.03.2024 00:49:59][INFO] Update id=740518546 is not handled. Duration 2 ms by bot id=6649228926
[01.03.2024 00:49:59][ERROR] Cause exception while process update id=740518546 by bot id=6649228926
ValidationError: 1 validation error for PlayerModel
hp
  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/greater_than_equal
Traceback (most recent call last):
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 156, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/handlers/rooms_manager.py", line 217, in in_game
    turn_result = room.make_turn(action, message.chat.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/core/scene.py", line 135, in make_turn
    action_results = self.shotgun.shot(player=target)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karo-work/buckshot-evo/app/core/shotgun.py", line 48, in shot
    player.take_damage(self.damage)
  File "/home/karo-work/buckshot-evo/app/core/player.py", line 83, in take_damage
    self.data.hp -= damage
    ^^^^^^^^^^^^
  File "/home/karo-work/miniconda3/envs/bask/lib/python3.11/site-packages/pydantic/main.py", line 786, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PlayerModel
hp
  Input should be greater than or equal to 0 [type=greater_than_equal, input_value=-1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.5/v/greater_than_equal
[01.03.2024 00:50:02][INFO] Update id=740518547 is handled. Duration 75 ms by bot id=6649228926
[01.03.2024 00:50:02][INFO] Update id=740518549 is handled. Duration 183 ms by bot id=6649228926
[01.03.2024 00:50:02][INFO] Update id=740518550 is handled. Duration 172 ms by bot id=6649228926
[01.03.2024 00:50:02][INFO] Update id=740518548 is handled. Duration 337 ms by bot id=6649228926
[01.03.2024 00:50:02][INFO] Update id=740518551 is handled. Duration 189 ms by bot id=6649228926
[01.03.2024 00:50:09][INFO] Update id=740518552 is handled. Duration 250 ms by bot id=6649228926
[01.03.2024 00:50:14][INFO] Update id=740518553 is handled. Duration 155 ms by bot id=6649228926
[01.03.2024 00:50:22][INFO] Update id=740518554 is handled. Duration 371 ms by bot id=6649228926
[01.03.2024 00:50:29][INFO] Update id=740518555 is handled. Duration 277 ms by bot id=6649228926
[01.03.2024 00:50:35][INFO] Update id=740518556 is handled. Duration 231 ms by bot id=6649228926
[01.03.2024 00:50:38][INFO] Update id=740518557 is handled. Duration 67 ms by bot id=6649228926
[01.03.2024 00:51:01][INFO] Update id=740518558 is handled. Duration 559 ms by bot id=6649228926
[01.03.2024 00:51:10][INFO] Update id=740518559 is handled. Duration 220 ms by bot id=6649228926
[01.03.2024 00:51:19][INFO] Update id=740518560 is handled. Duration 262 ms by bot id=6649228926
[01.03.2024 00:51:24][INFO] Update id=740518561 is handled. Duration 291 ms by bot id=6649228926
[01.03.2024 00:51:29][INFO] Update id=740518562 is handled. Duration 248 ms by bot id=6649228926
[01.03.2024 00:51:31][INFO] Update id=740518563 is handled. Duration 216 ms by bot id=6649228926
[01.03.2024 00:51:34][INFO] Update id=740518564 is handled. Duration 218 ms by bot id=6649228926
[01.03.2024 00:51:37][INFO] Update id=740518565 is handled. Duration 250 ms by bot id=6649228926
[01.03.2024 00:51:39][INFO] Update id=740518566 is handled. Duration 389 ms by bot id=6649228926
[01.03.2024 00:51:41][INFO] Update id=740518567 is handled. Duration 231 ms by bot id=6649228926
[01.03.2024 00:51:42][INFO] Update id=740518568 is handled. Duration 288 ms by bot id=6649228926
[01.03.2024 00:51:48][INFO] Update id=740518569 is handled. Duration 334 ms by bot id=6649228926
[01.03.2024 00:51:52][INFO] Update id=740518570 is handled. Duration 313 ms by bot id=6649228926
[01.03.2024 00:51:55][INFO] Update id=740518571 is handled. Duration 268 ms by bot id=6649228926
[01.03.2024 00:51:58][INFO] Update id=740518572 is handled. Duration 212 ms by bot id=6649228926
[01.03.2024 00:52:02][INFO] Update id=740518573 is handled. Duration 442 ms by bot id=6649228926
[01.03.2024 00:52:03][INFO] Update id=740518574 is handled. Duration 331 ms by bot id=6649228926
[01.03.2024 00:52:13][INFO] Update id=740518575 is handled. Duration 449 ms by bot id=6649228926
[01.03.2024 00:52:15][INFO] Update id=740518576 is handled. Duration 222 ms by bot id=6649228926
[01.03.2024 00:52:24][INFO] Update id=740518577 is handled. Duration 69 ms by bot id=6649228926
[01.03.2024 00:52:29][INFO] Update id=740518578 is handled. Duration 214 ms by bot id=6649228926
[01.03.2024 00:52:31][INFO] Update id=740518579 is handled. Duration 217 ms by bot id=6649228926
[01.03.2024 00:52:43][INFO] Update id=740518580 is handled. Duration 216 ms by bot id=6649228926
[01.03.2024 00:52:46][INFO] Update id=740518581 is handled. Duration 213 ms by bot id=6649228926
[01.03.2024 00:52:48][INFO] Update id=740518582 is handled. Duration 302 ms by bot id=6649228926
[01.03.2024 00:52:52][INFO] Update id=740518583 is handled. Duration 214 ms by bot id=6649228926
[01.03.2024 00:52:57][INFO] Update id=740518584 is handled. Duration 156 ms by bot id=6649228926
[01.03.2024 00:52:59][INFO] Update id=740518585 is handled. Duration 526 ms by bot id=6649228926
[01.03.2024 00:53:03][INFO] Update id=740518586 is handled. Duration 230 ms by bot id=6649228926
[01.03.2024 00:55:13][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 00:55:13][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 00:55:24][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 00:55:24][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 00:55:24][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 00:55:36][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:33:40][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:33:40][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:33:51][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:35:42][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:35:42][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:35:53][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:37:54][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:37:54][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:38:05][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:39:46][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:39:46][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:39:57][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:39:57][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:39:57][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:40:08][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:43:59][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:43:59][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:44:10][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:44:10][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:44:10][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:44:22][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:46:52][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:46:52][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:47:04][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:48:44][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:48:44][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:48:55][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 02:48:55][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 02:48:55][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 02:49:06][INFO] Connection established (tryings = 1, bot id = 6649228926)
[01.03.2024 18:23:40][ERROR] Failed to fetch updates - TelegramNetworkError: HTTP Client says - ServerDisconnectedError: Server disconnected
[01.03.2024 18:23:40][WARNING] Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6649228926)
[01.03.2024 18:23:51][INFO] Connection established (tryings = 1, bot id = 6649228926)
